simpleread.exe: simpleread.o
	g++ -g -o simpleread.exe simpleread.o -L/home/lucky/ASWF/oiio/OpenImageIO/dist/lib -lOpenImageIO_d

simpleread.o: simpleread.cpp
	g++ -c -g simpleread.cpp -I /home/lucky/ASWF/oiio/OpenImageIO/dist/include